language: php

git:
  depth: 10

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: 7.2
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
    - php: 7.3
    - php: 7.4

install:
  - composer validate
  - composer i --no-interaction --no-progress --no-suggest

script:
  - composer lint
  - composer test
